In [1]:
import sqlalchemy as db
import sys

sys.path.append("../conf")
from db_conn import engine

In [26]:
metadata = db.MetaData()

## Yahoo Prices

In [3]:
table = db.Table("yahoo_prices", metadata,
                 db.Column('date', db.DATE(), primary_key=True),
                 db.Column('stock_id', db.VARCHAR(10), primary_key=True),
                 db.Column('close', db.Float(), default=None),
                 db.Column('volume', db.Float(), default=None)
)

metadata.create_all(engine)

## OCDE

In [ ]:
table = db.Table("ocde", metadata,
                 db.Column('variable', db.VARCHAR(50), primary_key=True),
                 db.Column('period', db.VARCHAR(20), primary_key=True),
                 db.Column('period_type', db.VARCHAR(20), default=None),
                 db.Column('year', db.Integer(), default=None),
                 db.Column('quarter', db.Integer(), default=None),
                 db.Column('month', db.Integer(), default=None),
                 db.Column('value', db.Float(), default=None),
)

metadata.create_all(engine)

## CMF

In [27]:
table = db.Table("cmf", metadata,
                 db.Column('rut', db.Integer(), primary_key=True),
                 db.Column('fecha', db.DATE(), primary_key=True),
                 db.Column('moneda', db.VARCHAR(20), default=None),
                 db.Column('fecha_inicio', db.DATE(), default=None),
                 db.Column('fecha_termino', db.DATE(), default=None),
                 db.Column('ingreso', db.BIGINT(), default=None),
                 db.Column('ganancia', db.BIGINT(), default=None)

)

metadata.create_all(engine)

## Twitter

In [17]:
table = db.Table("twitter", metadata,
                 db.Column('id', db.BIGINT(), primary_key=True),
                 db.Column('created_at', db.DATETIME(), primary_key=True),
                 db.Column('full_text', db.VARCHAR(150), default=None),
                 db.Column('url', db.VARCHAR(100), default=None),
                 db.Column('hashtags', db.JSON(), default=None)
)

metadata.create_all(engine)

## Securities List

In [19]:
import pandas as pd

In [22]:
df = pd.read_excel('securities_data.xlsx')
df.dtypes

BBG Ticker     object
Yahoo ID       object
RUTSD           int64
RUTCD          object
TIPO           object
SBIF_ID       float64
Nombre         object
dtype: object

In [29]:
df.set_index('RUTSD', inplace =True)

In [25]:
df

,BBG Ticker,Yahoo ID,RUTSD,RUTCD,TIPO,SBIF_ID,Nombre
0,AESGENER CC,AESGENER.SN,94272000,94272000 - 9,NaN,NaN,AES Gener SA
1,AGUAS/A CC,AGUAS-A.SN,61808000,61808000 - 5,NaN,NaN,Aguas Andinas SA
2,ANDINAB CC,ANDINA-B.SN,91144000,91144000-8,NaN,NaN,Embotelladora Andina SA
3,BCI CC,BCI.SN,97006000,97006000-6,BANCO,16.0,Banco de Credito e Inversiones SA
4,BSAN CC,BSANTANDER.SN,97036000,97036000-K,BANCO,37.0,Banco Santander Chile
5,CAP CC,CAP.SN,91297000,91297000 -0,NaN,NaN,CAP SA
6,CCU CC,CCU.SN,90413000,90413000 - 1,NaN,NaN,Cia Cervecerias Unidas SA
7,CENCOSUD CC,CENCOSUD.SN,93834000,93834000 - 5,NaN,NaN,Cencosud SA
8,CHILE CC,CHILE.SN,97004000,97004000-5,BANCO,1.0,Banco de Chile
9,CMPC CC,CMPC.SN,90222000,90222000 - 3,NaN,NaN,Empresas CMPC SA
10,COLBUN CC,COLBUN.SN,96505760,96505760 - 9,NaN,NaN,Colbun SA
11,CONCHA CC,CONCHATORO.SN,90227000,90227000 - 0,NaN,NaN,Vina Concha y Toro SA
12,COPEC CC,COPEC.SN,90690000,90690000 - 9,NaN,NaN,Empresas COPEC SA
13,ECL CC,ECL.SN,88006900,88006900 - 4,NaN,NaN,Engie Energia Chile SA
14,ENELAM CC,ENELAM.SN,94271000,94271000 - 3,NaN,NaN,Enel Americas SA
15,ENELCHIL CC,ENELCHILE.SN,76536353,76536353 - 5,NaN,NaN,Enel Chile SA
16,ENTEL CC,ENTEL.SN,92580000,92580000 - 7,NaN,NaN,Empresa Nacional de Telecomunicaciones SA
17,FALAB CC,FALABELLA.SN,90749000,90749000 - 9,NaN,NaN,Falabella SA
18,IAM CC,IAM.SN,77274820,77274820 - 5,NaN,NaN,Inversiones Aguas Metropolitanas SA
19,ILC CC,ILC.SN,94139000,94139000 - 5,NaN,NaN,Inversiones La Construccion SA
20,ITAUCORP CC,ITAUCORP.SN,97023000,97023000-9,BANCO,39.0,Itau CorpBanca Chile SA
21,LTM CC,LTM.SN,89862200,89862200 - 2,NaN,NaN,Latam Airlines Group SA
22,MALLPLAZ CC,MALLPLAZA.SN,76017019,76017019 - 4,NaN,NaN,Plaza SA
23,PARAUCO CC,PARAUCO.SN,94627000,94627000 - 8,NaN,NaN,Parque Arauco SA
24,RIPLEY CC,RIPLEY.SN,99579730,99579730 - 5,NaN,NaN,Ripley Corp SA
25,SALFACOR CC,SALFACORP.SN,96885880,96885880 - 7,NaN,NaN,Salfacorp SA
26,SECUR CC,SECURITY.SN,97053000,97053000-2,BANCO,49.0,Grupo Security SA
27,SONDA CC,SONDA.SN,83628100,83628100 - 4,NaN,NaN,SONDA SA
28,SQM/B CC,SQM-B.SN,93007000,93007000 - 9,NaN,NaN,Sociedad Quimica y Minera de Chile SA
29,VAPORES CC,VAPORES.SN,90160000,90160000 - 7,NaN,NaN,Cia Sud Americana de Vapores SA

In [30]:
df.to_sql('securities', if_exists='replace', con=engine)